In [1]:
import numpy as np # 导入NumPy数学工具集
list=[1,2,3,4,5] # 创建列表
array_01=np.array([1,2,3,4,5]) # 列表转化成数组
array_02=np.array((6,7,8,9,10)) # 元组转化成数组
array_03=np.array([[1,2,3],[4,5,6]]) # 列表转化成2D数组
print ('列表：', list)
print ('列表转化为数组：', array_01)
print ('元组转化为数组：', array_02)
print ('2D数组：', array_03)
print ('数组的形状：', array_01.shape)
# print ('列表的形状：', list.shape) # 列表没有形状，程序会报错

列表： [1, 2, 3, 4, 5]
列表转化为数组： [1 2 3 4 5]
元组转化为数组： [ 6  7  8  9 10]
2D数组： [[1 2 3]
 [4 5 6]]
数组的形状： (5,)


In [2]:
array_04=np.arange(1,5,1) # 通过arange函数生成数组
array_05=np.linspace(1,5,5) # 通过linspace函数生成数组
print (array_04)
print (array_05)

[1 2 3 4]
[1. 2. 3. 4. 5.]


In [3]:
array_06 = np.arange(10)
print (array_06)
index_01 = array_06[3] # 索引-第4个元素
print ('第4个元素', index_01)
index_02 = array_06[-1] # 索引-最后一个元素
print ('第-1个元素', index_02)
slice_01 = array_06[:4] # 从0到4切片
print ('从0到4切片', slice_01)
slice_02 = array_06[0:12:4] # 从0到12切片，步长为2
print ('从0到12切片，步长为4', slice_02)

[0 1 2 3 4 5 6 7 8 9]
第4个元素 3
第-1个元素 9
从0到4切片 [0 1 2 3]
从0到12切片，步长为4 [0 4 8]


In [4]:
from keras.datasets import mnist #需要打开internet选项)
(X_train, y_train), (X_test, y_test) = mnist.load_data()
print (X_train.shape)
X_train_slice = X_train[10000:15000,:,:]

Using TensorFlow backend.


11493376/11490434 [==============================] - 1s 0us/step
(60000, 28, 28)


In [5]:
array_07 = np.array([[1,2,3],[4,5,6]])
print (array_07[1:2],'它的形状是', array_07[1:2].shape) 
print (array_07[1:2][0], '它的形状又不同了', array_07[1:2][0].shape)

[[4 5 6]] 它的形状是 (1, 3)
[4 5 6] 它的形状又不同了 (3,)


In [6]:
array_07 += 1 # 数组内全部元素加1
print (array_07)

[[2 3 4]
 [5 6 7]]


In [7]:
for i in range(array_07.shape[0]):
    for j in range(array_07.shape[1]):
        array_07[i,j] += 1

In [8]:
print (np.sqrt(array_07)) #打印每一个元素的平方根

[[1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [9]:
print (array_07,'形状是', array_07.shape) 
print (array_07.reshape(3,2), '形状是', array_07.reshape(3,2).shape)

[[3 4 5]
 [6 7 8]] 形状是 (2, 3)
[[3 4]
 [5 6]
 [7 8]] 形状是 (3, 2)


In [10]:
array_07 = array_07.reshape(3,2) #进行赋值才能改变数组本身

In [11]:
array_07 = array_07.T # 矩阵的转置

In [12]:
array_06 = np.arange(10)
print (array_06,'形状是', array_06.shape,'阶为', array_06.ndim) 
array_06 = array_06.reshape(10,1)
print (array_06,'形状是', array_06.shape,'阶为', array_06.ndim)


[0 1 2 3 4 5 6 7 8 9] 形状是 (10,) 阶为 1
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 形状是 (10, 1) 阶为 2


In [13]:
array_08 = np.array([[0,0,0], [10,10,10], [20,20,20], [30,30,30]])
array_09 = np.array([[0,1,2]])
array_10 = np.array([[0],[1],[2],[3]])
list_11 = [[0,1,2]]
print ('array_09的形状:', array_09.shape )
print ('array_10的形状:', array_10.shape )
array_12 = array_09.reshape(3)
print ('array_12的形状:', array_12.shape )
array_13 = np.array([1])
print ('array_13的形状:', array_13.shape )
array_14 = array_13.reshape(1,1)
print ('array_14的形状:', array_14.shape )
print ('08 + 09结果：',array_08 + array_09)
print ('08 + 10结果：',array_08 + array_10)
print ('08 + 11结果：',array_08 + list_11)
print ('08 + 12结果：',array_08 + array_12)
print ('08 + 13结果：',array_08 + array_13)
print ('08 + 14结果：',array_08 + array_14)

array_09的形状: (1, 3)
array_10的形状: (4, 1)
array_12的形状: (3,)
array_13的形状: (1,)
array_14的形状: (1, 1)
08 + 09结果： [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
08 + 10结果： [[ 0  0  0]
 [11 11 11]
 [22 22 22]
 [33 33 33]]
08 + 11结果： [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
08 + 12结果： [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
08 + 13结果： [[ 1  1  1]
 [11 11 11]
 [21 21 21]
 [31 31 31]]
08 + 14结果： [[ 1  1  1]
 [11 11 11]
 [21 21 21]
 [31 31 31]]


In [14]:
vector_01 = np.array([1,2,3])
vector_02 = np.array([[1],[2],[3]])
vector_03 = np.array([2])
vector_04 = vector_02.reshape(1,3)
print ('vector_01的形状:', vector_01.shape)
print ('vector_02的形状:', vector_02.shape)
print ('vector_03的形状:', vector_03.shape)
print ('vector_04的形状:', vector_04.shape)
print ('01和01的点积:', np.dot(vector_01,vector_01))
print ('01和02的点积:', np.dot(vector_01,vector_02))
print ('04和02的点积:', np.dot(vector_04,vector_02))
print ('01和数字的点积:', np.dot(vector_01,2))
print ('02和03的点积:', np.dot(vector_02,vector_03))
print ('02和04的点积:', np.dot(vector_02,vector_04))
# print ('01和03的点积:', np.dot(vector_01,vector_03)) # 程序会报错
# print ('02和02的点积:', np.dot(vector_02,vector_02))

vector_01的形状: (3,)
vector_01的形状: (3, 1)
vector_01的形状: (1,)
vector_01的形状: (1, 3)
01和01的点积: 14
01和02的点积: [14]
04和02的点积: [[14]]
01和数字的点积: [2 4 6]
02和03的点积: [2 4 6]
02和04的点积: [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [15]:
matrix_01 = np.arange(0,6).reshape(2,3)
matrix_02 = np.arange(0,6).reshape(3,2)
print(matrix_01)
print(matrix_02)
print ('01和02的点积:', np.dot(matrix_01,matrix_02))
print ('02和01的点积:', np.dot(matrix_02,matrix_01))
print ('01和01的点积:', np.dot(matrix_01,matrix_01))

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
01和02的点积: [[10 13]
 [28 40]]
02和01的点积: [[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)